// ui/frontend/components/ui/input.tsx
// Copyright © 2026 Hypermesh Foundation. All rights reserved.
// Licensed under the Business Source License 1.1.
// See the LICENSE file in the repository root for full license text.

import * as React from "react"

import { cn } from "@/lib/utils"

function Input({ className, type, ...props }: React.ComponentProps<"input">) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(
        "file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-input flex h-9 w-full min-w-0 rounded-md border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
        "focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px]",
        "aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive",
        className
      )}
      {...props}
    />
  )
}

export { Input }

// caesar/scrolls-app/satchel-wallet-svelte/src/lib/components/ui/Input.svelte
<script>
  import { cn } from "../../utils/cn.js";
  
  let className = "";
  export { className as class };
  export let value = "";
  export let type = "text";
  export let placeholder = "";
  export let disabled = false;
  export let required = false;
  
  $: classes = cn(
    "flex h-10 w-full rounded-md border px-3 py-2 text-sm transition-colors",
    "border-gray-600 bg-gray-900 text-white placeholder:text-gray-400",
    "focus:border-yellow-400 focus:outline-none focus:ring-2 focus:ring-yellow-400/20",
    "disabled:cursor-not-allowed disabled:opacity-50",
    className
  );
</script>

<input
  class={classes}
  bind:value
  {type}
  {placeholder}
  {disabled}
  {required}
  {...$$restProps}
  on:change
  on:input
  on:focus
  on:blur
/>
